# Generated by Django 6.0.6 on 2026-07-13 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('author_name', models.CharField(default='Fora AI Team', max_length=100)),
                ('excerpt', models.CharField(help_text='One or two sentences shown on the blog listing and used as the meta description if none is set.', max_length=280)),
                ('cover_emoji', models.CharField(default='🛡️', help_text='Small visual mark shown on the listing card', max_length=8)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('body_html', models.TextField(help_text='Full article content as HTML')),
                ('meta_title', models.CharField(blank=True, help_text='Overrides <title> tag if set', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Overrides excerpt for SEO if set', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
