# Generated by Django 6.0.6 on 2026-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in INR for Razorpay. e.g. 199 for monthly, 2330 for yearly', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='scan_limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('upi', 'UPI (Manual)'), ('', 'Free / Manual')], max_length=20),
        ),
    ]
