# Generated by Django 6.0.6 on 2026-07-13 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_database_override', models.BooleanField(default=False, help_text='If enabled, the provider selected here overrides the AI_PROVIDER environment variable.')),
                ('active_provider', models.CharField(choices=[('mock', 'Rule Engine Only (no AI key required)'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('groq', 'Groq')], default='mock', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes, e.g. rate-limit reminders or which API key is currently active.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='Untitled Scan', max_length=255)),
                ('source_type', models.CharField(choices=[('paste', 'Pasted Code'), ('file', 'Uploaded File'), ('zip', 'ZIP Project')], default='paste', max_length=10)),
                ('language', models.CharField(blank=True, help_text='Detected primary language', max_length=30)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('raw_code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('security_score', models.PositiveSmallIntegerField(default=100)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('ai_provider_used', models.CharField(default='mock', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('lines_of_code', models.PositiveIntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g. SQL Injection, XSS, CSRF', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('owasp_reference', models.CharField(blank=True, max_length=100)),
                ('cwe_reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('why_dangerous', models.TextField()),
                ('recommended_fix', models.TextField()),
                ('secure_code_example', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='scanner.scan')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='scanner.scannedfile')),
            ],
            options={
                'ordering': ['severity', 'title'],
            },
        ),
    ]
