# Generated by Django 5.1.4 on 2026-07-23 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_name', models.CharField(default='Untitled AI', max_length=255)),
                ('target_url', models.URLField(max_length=500)),
                ('request_field', models.CharField(default='message', help_text='JSON field name the target endpoint expects for the user message', max_length=100)),
                ('response_path', models.CharField(default='response', help_text="Dot-path to the reply text inside the target's JSON response, e.g. 'data.reply'", max_length=200)),
                ('auth_header', models.CharField(blank=True, help_text='Optional Authorization header value sent with every test request', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveSmallIntegerField(default=0)),
                ('current_step_label', models.CharField(blank=True, max_length=255)),
                ('security_score', models.PositiveSmallIntegerField(default=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('jailbreak_score', models.PositiveSmallIntegerField(default=100)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.PositiveIntegerField(default=0)),
                ('error_rate_pct', models.FloatField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prompt_injection', 'Prompt Injection'), ('jailbreak', 'Jailbreak'), ('prompt_leak', 'Prompt Leak'), ('sensitive_data', 'Sensitive Data Leak'), ('harmful_content', 'Harmful Content'), ('response_quality', 'Response Quality')], max_length=30)),
                ('test_name', models.CharField(max_length=255)),
                ('prompt_sent', models.TextField()),
                ('response_snippet', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=True)),
                ('severity', models.CharField(default='low', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('had_error', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='ai_scanner.aiscan')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
