# Generated by Django 5.1.4 on 2026-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscan',
            name='target_format',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('openai_compatible', 'OpenAI-compatible chat completions'), ('custom_json_chat', 'Custom JSON chat endpoint'), ('plain_text_chat', 'Plain-text chat endpoint')], default='unknown', help_text='What the pre-flight probe detected the target endpoint to be.', max_length=20),
        ),
    ]
