# Generated by Django 5.1.4 on 2026-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_scanner', '0002_aiscan_target_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscan',
            name='api_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='bearer_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='custom_headers_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted JSON blob of extra headers, e.g. {"X-Org-Id": "..."}'),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='model_name',
            field=models.CharField(blank=True, help_text='Optional model identifier to send with each request (e.g. gpt-4o-mini), for API endpoints that require one.', max_length=100),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='owasp_summary',
            field=models.JSONField(blank=True, default=list, help_text='Precomputed OWASP LLM Top 10 mapping table for this scan (see engine.scoring.build_owasp_summary).'),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='request_body_template',
            field=models.TextField(blank=True, help_text='Optional custom JSON request body. Use {{prompt}} where the test prompt should go and, optionally, {{model}} for model_name. Leave blank to use request_field/response_path instead.'),
        ),
        migrations.AddField(
            model_name='aiscan',
            name='target_type',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('website', 'Public AI website / chat interface'), ('api_endpoint', 'AI API endpoint'), ('agent', 'Custom AI agent'), ('rag', 'RAG application'), ('saas', 'AI SaaS product')], default='auto', help_text='What kind of AI target this is. Auto-detect picks the right test profile from the pre-flight probe.', max_length=20),
        ),
        migrations.AddField(
            model_name='aitestresult',
            name='owasp_llm_id',
            field=models.CharField(blank=True, help_text='OWASP LLM Top 10 mapping, e.g. LLM01, LLM06 (blank for tests outside that framework)', max_length=10),
        ),
        migrations.AlterField(
            model_name='aiscan',
            name='auth_header',
            field=models.TextField(blank=True, help_text='Optional Authorization header value sent with every test request (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='aitestresult',
            name='category',
            field=models.CharField(choices=[('prompt_injection', 'Prompt Injection'), ('jailbreak', 'Jailbreak'), ('prompt_leak', 'System Prompt Leakage'), ('sensitive_data', 'Sensitive Data Leakage'), ('harmful_content', 'Harmful Content Generation'), ('multi_turn', 'Multi-turn Attack'), ('tool_abuse', 'Tool / Function Calling Abuse'), ('rag_security', 'RAG Security'), ('response_consistency', 'Response Consistency'), ('context_injection', 'Context Injection'), ('encoding_attack', 'Encoding & Translation Attack'), ('indirect_injection', 'Indirect Prompt Injection'), ('hidden_instruction', 'Hidden Instruction Attack'), ('agent_manipulation', 'Agent Manipulation'), ('api_misuse', 'API Misuse / Parameter Manipulation'), ('unauthorized_exposure', 'Unauthorized Data Exposure'), ('memory_leakage', 'Memory Leakage'), ('alignment', 'AI Safety & Alignment'), ('response_quality', 'Response Quality')], max_length=30),
        ),
    ]
